### ISSUE TITLE
"Amount to Send" unit is wrong

### ISSUE THREAD

**Issue by woniesong92** [ChengOrangeJu/WebExtensionWallet#12]
![image](https://user-images.githubusercontent.com/2935309/39971730-260b69e2-56b5-11e8-9a02-045afcc92afc.png)

To reproduce:

```
const nebPay = new NebPay()
const value = "1000000"
const callFunction = "anyFunction"
const callArgs = JSON.stringify([idx])
const opts = {
}

nebPay.call(
  CONTRACT_ADDRESS,
  value,
  callFunction,
  callArgs,
  opts
)
```

The first time extension popup is open, the unit for value is wrong.

**Comment by yupnano** [comment]
Thanks for your feadback, we will fix this bug later.

**Comment by yupnano** [comment]
This bug has fixed, thanks.

**Comment by woniesong92** [comment]
Nice, do you need help with other things by the way?

**Comment by yupnano** [comment]
Do you have interest in developing a browser extension like metamask for Ethereum?

**Comment by woniesong92** [comment]
@yupnano sure, I have experience with building Chrome extensions (e.g. https://howonsong.com/work/instantmusic)
