### ISSUE TITLE
请问你花了多少时间开发这个？

### ISSUE THREAD

**Issue by flyq** [ChengOrangeJu/WebExtensionWallet#15]
请问大概花了几天开发这个？基于星云链的web钱包开发的吧？然后大概遇到了一些什么坑能不能分析？
谢谢大神~

**Comment by yupnano** [comment]
因为之前没弄过浏览器插件，所以鼓捣了大概两周吧，基本可以用了。后来再根据反馈修修补补。
这个是把web-wallet塞到插件里，后台处理下通信。

**Comment by cyy13** [comment]
我现在需要开发另一个虚拟币的的Chrome插件钱包，可能会遇到一些问题，到时向您请教~

**Comment by flyq** [comment]
好的，感谢~

**Comment by yupnano** [comment]
@cyy13 好呀，可以一块交流学习。
