### ISSUE TITLE
[Suggestion] Add a "reject all" button

### ISSUE THREAD

**Issue by remiroyc** [ChengOrangeJu/WebExtensionWallet#16]
If you stack a lot pending transactions. Wouldn't it be nice to have a "reject all" button to cancel all pending transactions?

**Comment by yupnano** [comment]
sure, this is a useful suggestion, I'll try to add this button within this week.

**Comment by yupnano** [comment]
This button has added, if numbers of transactions need to be processed is more than 1, then this button will show.
