### ISSUE TITLE
[Suggestion] I wish 'WebExtensionWallet' had a unique name.

### ISSUE THREAD

**Issue by JonJee** [ChengOrangeJu/WebExtensionWallet#18]
I wish 'WebExtensionWallet' had a unique name such as metamask of Ethereum.

Why don't we get a unique name of wallet?

thanks

**Comment by yupnano** [comment]
It's just an beta version now. And it's functionality is still very limited.
It's doesn't deserve a special name for now. 😭

**Comment by JonJee** [comment]
fair enough

thank you for replying.
