### ISSUE TITLE
Extension wallet is not installed, please install it first.

### ISSUE THREAD

**Issue by xulove** [ChengOrangeJu/WebExtensionWallet#2]
i hava installed the WebExtensionWallet by your "README.md",
but when I open "testPage.html" in the "test" folder,show "Extension wallet is not installed, please install it first.".how do I solve it ?
thanks!

**Comment by yupnano** [comment]
Sorry that there was a bug in the testpage when checking extension. Please pull the leatest repo and try again.

**Comment by xulove** [comment]
I have solve the problem,thanks

**Comment by yupnano** [comment]
yes, this is the bug.
