### ISSUE TITLE
选择钱包文件选择不上

### ISSUE THREAD

**Issue by addinGao** [ChengOrangeJu/WebExtensionWallet#4]
点击ｗｅｂ钱包插件，发送星云币－＞选择钱包－＞选择完钱包后，ｗｅｂ钱包插件界面自动没了，打开又要选择钱包，周而复始．请问是什么问题？

**Comment by yupnano** [comment]
如果签报文件成功导入后悔自动保存的，再次打开插件后会自动导入之前的钱包文件。这时用户仍然可以选择替换为其他钱包，所以还是有“选择钱包文件”的按钮。

![default](https://user-images.githubusercontent.com/5012612/39682578-55234e4c-51e3-11e8-9f11-bf1f8a988adf.png)

**Comment by 7Light** [comment]
屁，选择上次文件以后啥反应没有，重新打开还是没有，根本用不了

**Comment by 7Light** [comment]
上传完文件以后啥反应没有，重新打开插件还是跟以前没导入一样，根本用不了

**Comment by yupnano** [comment]
@7Light 请问你用的是什么系统呢? 
我刚注意到在linux系统中，在插件页面打开文件选择对话框时，插件页面会被关闭，所以无法完成文件选择过程。这个应该是linux系统的问题，比如matamask等浏览器插件在linux下也无法选取文件的。
由于目前钱包只能通过文件导入的方式，所以目前只能在windows和MAC系统下使用该插件。

**Comment by 7Light** [comment]
WIN7,现象就跟你说的一样，选择完文件，页面插件就自动关闭了，我一会换一台电脑试试

**Comment by yupnano** [comment]
我也是用的win10， chrome 66.0.3359.139
这边操作没有遇到过这种问题。你再试试看，还有问题的话我再找找原因。

**Comment by 7Light** [comment]
我在WIN10上试了一下，确实是能跑通了，但是我的主要开发环境还是在win7上，还是希望您可以解决，感谢

**Comment by 7Light** [comment]
WIN7我试了4台PC都不行

**Comment by yupnano** [comment]
暂时有个办法，你可以在弹出的发送交易界面导入钱包文件，这个界面是个网页，不会自动关闭。
在插件页面导入文件的问题我再想想办法。

**Comment by 7Light** [comment]
。。我没发现什么办法能调出发送的界面，因为调用发送会直接报错提示要先导入钱包文件，不会弹出插件

**Comment by yupnano** [comment]
你用 example/example.html，点击第一个按钮就会弹出支付界面。
https://github.com/ChengOrangeJu/WebExtensionWallet/blob/master/example/TestPage_new.html

**Comment by 7Light** [comment]
我可不可以通过什么方法规避一下，比如说直接把文件放到某个目录下就行

**Comment by 7Light** [comment]
好的，我试试example,谢谢

**Comment by 7Light** [comment]
搞定了，兄弟，谢谢
