### ISSUE TITLE
请问有获取当前使用插件的用户钱包地址吗

### ISSUE THREAD

**Issue by frankwei98** [ChengOrangeJu/WebExtensionWallet#8]
我们需要显示用户钱包的头像

**Comment by yupnano** [comment]
you can use [Using postMessage](https://github.com/ChengOrangeJu/WebExtensionWallet#31-using-postmessage) method to get user address for now. 
We will design a SDK and add more interface in the future.

**Comment by yupnano** [comment]
https://github.com/nebulasio/WebExtensionWallet/issues/6
